config/nginx/conf.d/fastcgi.conf
fastcgi cache should only cache pages with certain http response codes instead of "any" which can sometimes cache transient 5XX error pages. this patch changes the caching behavior so that it only caches 200, 301, 302, and 404.
see http://community.rtcamp.com/t/fascgi-cache-caching-error-pages/3847
=> Cache only certain response codes

src/lib/ee_lib_variables.sh
vimbadmin version updated to 3.0.11, this should resolve database issues at post-installation.
=> updated vimbadmin version

ee/cli/plugins/stack.py
https://github.com/EasyEngine/easyengine/issues/677
volatile-lru is a poor choice as it depends on the keys stored to be explicitly marked as purgable, something that the WordPress Redis plugin DOES NOT do. This means that an EE server running Redis will fill the cache, never to clean it unless it's purged via the Nginx plugin.
Setting it to allkeys-lru ensures that the oldest used keys are always purged if out of RAM instead of segfaulting and massively slowing down a WordPress site.
=> Fix Redis config volatile-lru -> allkeys-lru

ee/cli/plugins/site.py
`min_expiry_days` is set to 30 days, but the log warning says 60.
=> Log warning for not renewing from 60 to 30

ee/cli/templates/redis-hhvm.mustache, ee/cli/templates/redis-php7.mustache, ee/cli/templates/redis.mustache, ee/cli/templates/w3tc-hhvm.mustache, ee/cli/templates/w3tc-php7.mustache, ee/cli/templates/w3tc.mustache, ee/cli/templates/wpfc-hhvm.mustache, ee/cli/templates/wpfc-php7.mustache, ee/cli/templates/wpfc.mustache, ee/cli/templates/wpsc-hhvm.mustache, ee/cli/templates/wpsc-php7.mustache, ee/cli/templates/wpsc.mustache
If the woocoomerce cookie for the cart is set the user shouldn't get pages from cache, so added the woocommerce cookie to the skip cache rules for nginx.
=> Woocommerce: Cache shows cart items from other users

php/commands/secure.php
As `ee secure --port` and `ee secure --ip` was not at all implemented,
I ported command `ee secure --port` and `ee secure --ip` which is linked down below,
>https://easyengine.io/docs/commands/secure/
=> Ported command 'ee secure'

ee/cli/templates/redis-hhvm.mustache, ee/cli/templates/redis-php7.mustache, ee/cli/templates/redis.mustache, ee/cli/templates/w3tc-hhvm.mustache, ee/cli/templates/w3tc-php7.mustache, ee/cli/templates/w3tc.mustache, ee/cli/templates/wpfc-hhvm.mustache, ee/cli/templates/wpfc-php7.mustache, ee/cli/templates/wpfc.mustache, ee/cli/templates/wpsc-hhvm.mustache, ee/cli/templates/wpsc-php7.mustache, ee/cli/templates/wpsc.mustache
Changed skip_cache flag triggers to be more inclusive with respect to multiple alternative WordPress shopping cart and xml sitemap plugins, not just Woo and Yoast... Now also Easy Digital Downloads, XML Sitemap + Google News Feeds, Better XML Sitemaps and XML Sitemap Generator.
=> Skip cache for more cart and sitemap plugins

install
Issue was reported on EE Community Forum : 
http://community.rtcamp.com/t/ubunut-17-04-or-17-10/9753
=> Add Ubuntu 16.04 LTS in the compatible OS list

ee/cli/templates/wpcommon-php7.mustache, ee/cli/templates/wpcommon.mustache
These sitemap rules are not needed for the yoast sitemaps to function whilst breaking other sitemap plugins.
Adresses https://github.com/EasyEngine/easyengine/issues/601 and https://github.com/sybrew/the-seo-framework/issues/107
=> Remove redundant Yoast sitemap rules

ee/core/mysql.py
PyMySQL is not a drop in replacement for pymysql3 and as such it throws different exceptions. We are creating our own exceptions and when pymysql3 was replaced by PyMySQL, we were not returning the correct value in one situation. #969 
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> Fix pymysql related error

.travis.yml, ci/deploy.sh, ci/prepare.sh, composer.lock
Setup travis-ci for automated phar building.
Add deployment and preparation scripts.
Fix #978
=> Setup travis-ci for phar building

ci/deploy.sh, composer.lock
Update `.travis.yml` to incorporate automatic docker image building with the latest `phar` as soon as the new `phar` is generated.
=> Add CI build for docker images and update to wp-command

ee/cli/templates/locations-php7.mustache, ee/cli/templates/locations.mustache
Say someone writes a page or post about the game Ping Pong or a television animation Pingu or an urban dictionary about PMA (Positive Mental Attitude). It'd be likely that page slug would start with "ping" or "pma". In such a case, visiting that page would give an unexpected result.
This can be prevented by making the location directives in locations.conf and locations-php7.conf more strict by:
- terminating the location regex for /ping and /status with a $
- adding = to location directives /pma, /adminer etc.
=> All URI starting with /status, /ping, /pma, /adminer etc. are treated as special locations

ee/core/download.py
The urlretrieve function used to download the update script is deprecated. Plus rt.cx is now served over HTTPS and urlretrieve can't handle redirection.
Replaced the deprecated function with urlopen as it can also handle redirection.
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> Replace deprecated urlretrieve() with request.urlopen()

README.md
Docker for Mac has limited filesystem access. https://github.com/EasyEngine/easyengine/issues/1059. Currently removing MacOS installation instructions until further testing.
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> Remove MacOS install instructions

README.md
Signed-off-by: Mriyam Tamuli <mbtamuli@gmail.com>
=> Add command examples to README

php/class-ee.php, php/utils.php
Extend `EE::launch` and `default_launch` functions to accommodate environment variables and working dir to execute the command in. 
Also have added `default_exec` and `default_shell_exec` functions in `utils` to execute `exec()` and `shell_exec()` with debugging and logging on terminal as well as file.
=> Extend EE::launch to accomodate environment variables

php/class-ee-docker.php
Closes https://github.com/EasyEngine/easyengine/issues/1078.
=> Fix deprecated warning in php7.2

php/commands/src/CLI_Command.php
There's a bug in beta-1 release in which when you issue update, It threw error (but the update worked correctly). 
The error was thrown because after update, the phar is replaced and after that we're calling `EE::success` which triggers autoloading. The autoloader cannot find the class as the phar has been moved.
To solve it, we autoloaded the given class before the phar was moved.
=> Fix update bug

composer.json, composer.lock, php/AcmePhp/Cli/Exception/AcmeCliActionException.php, php/AcmePhp/Cli/Exception/AcmeCliException.php, php/AcmePhp/Cli/Exception/AcmeDnsResolutionException.php, php/AcmePhp/Cli/Exception/CommandFlowException.php, php/AcmePhp/Cli/Repository/Repository.php, php/AcmePhp/Cli/Repository/RepositoryInterface.php, php/AcmePhp/Cli/Repository/RepositoryV2Interface.php, php/AcmePhp/Cli/Serializer/PemEncoder.php, php/AcmePhp/Cli/Serializer/PemNormalizer.php, php/EE/Bootstrap/LoadSiteUtilityFunctions.php, php/EE/Bootstrap/RouteSiteCommands.php, php/EE/Dispatcher/CommandFactory.php, php/EE/DocParser.php, php/EE/Runner.php, php/bootstrap.php, php/class-ee-db.php, php/class-ee-site-letsencrypt.php, php/class-ee-site-shutdown-handler.php, php/class-ee-site.php, php/init-ee.php, php/site-utils.php, php/utils.php
Closes: https://github.com/EasyEngine/easyengine/issues/1060
* Make Site-Command Abstract
* Add logic for routing according to `--type` parameter.
* Add functionality to ignore registration of public functions using `@ignorecommand` annotation.
* Add functionality to inherit command doc-comment from parent using `@inheritdoc` annotation.
* Add site-utils for common functions across site-packages.
=> Update support for packaging site command

php/EE/Runner.php
Add support for old ee3 site creation parameters.
Converts the old `--wp, --wpsubdom, --wpsubdir, --wpredis` to the new `--type` syntax internally.
example:
`ee site create example.com --wpsubdom` => `ee site create example.com --type=wp --wpsubdom`
=> Add support for ee3 site creation parameters

.travis.yml, features/bootstrap/FeatureContext.php, php/class-ee-docker.php, php/class-ee-site.php, php/class-ee.php, php/commands/src/CLI_Command.php, php/site-utils.php, php/utils.php
Closes https://github.com/EasyEngine/easyengine/issues/1139
Breaking changes. Need functional call changes in following post this:
https://github.com/easyengine/site-command/
https://github.com/easyengine/site-wp-command/
https://github.com/easyengine/cron-command/
=> Update debugging flow

php/EE/Runner.php
Remove extra assoc_arg deletion in support for ee3 to ee4 command syntax conversion.
=> Remove extra assoc_arg deletion

composer.json, composer.lock, php/class-ee-site.php, php/site-utils.php, templates/custom.conf.mustache
Closes https://github.com/EasyEngine/easyengine/issues/1136
Added custom nginx configuration to fix `413 - Entity Too Large` issue.
=> Fix multiple issues

php/site-utils.php
=> Update site-utils to start specific site containers

img-versions.json, php/EE/Migration/Containers.php, php/site-utils.php, php/utils.php
Closes https://github.com/EasyEngine/easyengine/issues/1156
=> Add support to independently version docker images

.travis.yml, php/class-ee-db.php, php/class-ee-site-letsencrypt.php, php/class-ee-site.php, php/site-utils.php, templates/redirect.conf.mustache, utils/make-phar.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1170 and https://github.com/EasyEngine/site-command/issues/77
Other than that, this PR  - 
1. corrects SSL behaviour as discussed with team(use --ssl and --wildcard instead of --le).
2. Adds WWW domain while requesting cert - https://github.com/EasyEngine/easyengine/pull/1171/commits/c57626365d16e2f3d863c9a6c8adae92a6b849c2
3. Adds function to reload ee-nginx-proxy container - https://github.com/EasyEngine/easyengine/pull/1171/commits/192fdc45a18ab116834e8dd74ee9ecb4586f270a
4. Fix http challenge creation - https://github.com/EasyEngine/easyengine/pull/1171/commits/6977a1df104fbcf4f788541d51e8d07d5ccc3314
5. Add ability to inherit cert - https://github.com/EasyEngine/easyengine/pull/1171/commits/f74c8e199030ba9103e3294558a67afa7db2 …
=> Ssl wildcard all site types

php/class-ee-docker.php, php/class-ee-site.php, php/site-utils.php, templates/global_docker_compose.yml.mustache
Moves global containers like `ee-cron-scheduler` and `ee-nginx-proxy` to global `docker-compose.yml`. This way "services" in easyengine can then easily be managed by service command - https://github.com/EasyEngine/easyengine/issues/1010.
Earlier it used to be that there was a single network per site and nginx-proxy was connected to it.
Now there is a special `ee-global-network` network. All nginx containers of all sites will be connected to it and there will be seperate site-name network in which all containers of same site will connect. 
Depends on - https://github.com/EasyEngine/site-command/pull/99 and https://github.com/EasyEngine/site-wp-command/pull/24
**NOTE**: Travis-CI will not pass until dependent PRs are merged
=> Move global containers to docker-compose

php/EE/Migration/Containers.php, php/init-ee.php
Depends on https://github.com/EasyEngine/service-command/pull/5. Make sure to merge both PRs together.
=> Replace ee-nginx-proxy with EE_PROXY_TYPE constant

php/utils.php
Issue ref - https://github.com/EasyEngine/easyengine/issues/1231
=> Move get_curl_info to EE utils

php/EE/Model/Option.php
Currently while triggering migrations it shows warning that non static method Option::get is being called statically. This PR is to fix it.
=> Make get and set methods in Option model static

php/EE/Migration/Containers.php
issue ref: https://github.com/EasyEngine/site-command/issues/153
=> Change old column names with new ones

php/EE/Model/Base.php
Fixes https://github.com/EasyEngine/site-command/issues/159
=> Fix saving and getting boolean value in db

php/class-ee-docker.php
Utility function required for: https://github.com/EasyEngine/site-command/pull/176
=> Add docker-compose service check

php/class-ee-docker.php
Functions created to facilitate https://github.com/EasyEngine/site-command/pull/188
=> Add docker volume functions

img-versions.json, migrations/db/20181016052850_easyengine_insert_docker_images_version.php, php/EE/Migration/Containers.php
=> Add support for PHP 5.6

README.md, ci/prepare.sh, php/EE/Runner.php, php/commands/src/CLI_Command.php
Closes: https://github.com/EasyEngine/easyengine/issues/1308
=> Update checks and migration triggering

php/utils.php
Issue ref: https://github.com/EasyEngine/site-command/issues/241
=> Add resolve to locahost capability in curl utility

php/commands/src/CLI_Command.php
Disable cli update for macOS, instead prompt to run `brew upgrade easyengine`.
=> Disable cli update for macOS

.travis.yml, ci/deploy.sh, composer.json
Remove dev dependencies before creating phar for deployment as they have special ext requirements that are not needed by default in EE.
=> Update phar build script

php/EE/Runner.php
docker-compose command for `EE_PROXY_TYPE` will not run on `ee` -> `cli`, `config` and `help`
:heavy_check_mark: Improves performance.
=> Fix docker-compose command being ran on cli, config and help

img-versions.json, php/EE/Migration/Containers.php
I've ensured that the default is still 7.4. If `--php=8.0` is specified, only then 8.0 site will be created
Depends on:
https://github.com/EasyEngine/site-command/pull/380
https://github.com/EasyEngine/site-type-php/pull/85
https://github.com/EasyEngine/site-type-wp/pull/192
=> Add PHP 8.0 support in site create

migrations/db/20181016052850_easyengine_insert_docker_images_version.php
This pull request enhances the Docker image pulling process in the `InsertDockerImagesVersion` migration by introducing concurrent downloads and updating the list of images to be pulled. The main improvements focus on performance and maintainability by leveraging Symfony's `Process` class to pull multiple images in parallel.
**Performance and process management:**
* Added concurrent Docker image pulling using Symfony's `Process` class, allowing up to four images to be pulled simultaneously instead of sequentially. This significantly speeds up the migration process.
* Implemented a queue system for managing image pulls and tracking successful downloads, improving reliability and error handling during migration.
**Dependency and image updates:**
* Imported …
=> feat(migrations): implement concurrent docker image pulls
