EasyEngine/easyengine

- ee/cli/plugins/site_functions.py
> Add dbhost to wp-config create function

- ee/cli/plugins/stack.py
> error in help

- ee/cli/plugins/site_functions.py
This pull request tries to fix some of the strings from #674
> updated the WordPress rademark in some strings

- README.md
Updated supported Operating system to include 16.04
> Added 16.04 on line 11

- install
Use `ee_lib_echo_fail` function after it is defined.
> Update install script.

- .travis.yml
- README.md
- Vagrantfile
- install
Added Vagrantfile and information about it in the README.
Also added slack notifications for travis builds.
> Vagrantfile and Slack Notifications

- php/utils/file-utils.php
> fixed 'ee_file_search_replace' when file not found

- php/class-ee.php
- php/commands/debug.php
the debug command used earlier was not working from the PHP script which was working fine from bash. so replaced it with the one that works.
> fix global nginx debug

- php/commands/site.php
Showing notice when executing force delete command
> WIP : Fix - PHP Notice

- php/commands/clean.php
- php/commands/info.php
1. Update coding standard
2. Add PHP ConfigParser
> WIP: Fix/info command

- install
I haven't ran it on my machine as I don't have ubuntu(I have mac). I've dry ran it on my college's machine and it looked fine.
> Fixed errors in ee update command

- install
Reverts EasyEngine/easyengine#952
> Revert "Fixed errors in ee update command"

- php/EE/Runner.php
- php/commands/src/CLI_Command.php
- php/config-spec.php
Enable and Add Update feature: `ee cli update`
> Add update feature

- php/class-ee-docker.php
Keeping letsencrypt only in site for time being.
> Remove letsencrypt from mail

- php/EE/Runner.php
Fix exit-code 1 issue while using the help flag.
> Add help flag compatiblity

- composer.lock
- ee4-config/wpredis-subdir/config/nginx/common/redis.conf
- ee4-config/wpredis-subdir/config/nginx/common/wpsubdir.conf
- ee4-config/wpredis-subdir/config/nginx/default.conf
- ee4-config/wpsubdir/config/nginx/common/php.conf
- php/class-ee-docker.php
Add config files for multi-site Redis caching.
> Redis caching for multi-site

- composer.lock
- php/class-ee-db.php
- php/utils.php
Update db schema for site info.
Add utility function for tabular display of info.
> Update for site info

- ee/core/variables.py
This prevents ee comand to execute.
> [High importance] Variables.py indentation fix

- php/class-ee-docker.php
> WIP: Add letsencrypt feature

- ee4-config/wpredis-subdir/config/nginx/common/redis.conf
- ee4-config/wpredis/config/nginx/common/redis.conf
- php/EE/Runner.php
- php/class-ee-db.php
- php/class-ee-docker.php
> WIP: Updates for per site redis

- docs/build-and-release.md
- docs/core-repo-structure.md
- docs/developer-docs.md
- docs/docker-files.md
- docs/structure-for-multiple-repos.md
- docs/test-documentation.md
> v4 Documentation

- php/EE/Runner.php
- php/class-ee.php
- php/config-spec.php
Remove `--allow-root` flag to allow `ee` using `root` user.
Closes #1035
> Remove allow root flag

- docs/core-repo-structure.md
- php/EE/Runner.php
- php/class-ee.php
- php/commands/src/CLI_Command.php
- php/init-ee.php
- utils/make-phar.php
Some instances have been intentionally left out.
1. `ee4-config` folder - It'll be removed in https://github.com/EasyEngine/easyengine/pull/1040
2. `php/class-ee-docker.php` - It'll be refactored in https://github.com/EasyEngine/easyengine/pull/1041
> Changed ee4 instances to ee

- php/EE/Runner.php
- php/commands/src/CLI_Command.php
The migration will be worked upon in the next version/s.
> Fix and extend update function

- composer.json
- composer.lock
Removing wp-command for now as there are some issues pending with it. It will either be introduced in later versions or replaced by a better command.
> Update composer json and lock

- php/EE/Runner.php
- php/init-ee.php
Ask for sudo only at entrypoint. 
Remove sudo from other places.
Correct error message.
> Confirmed sudo at entrypoint

- php/class-ee-docker.php
Looks like I missed this one while on - https://github.com/EasyEngine/easyengine/pull/1079.
> Fix deprecated warning while disconnecting site.

- php/commands/src/CLI_Command.php
Closes https://github.com/EasyEngine/easyengine/issues/1088
> Add check-update command

- features/bootstrap/FeatureContext.php
- features/cli.feature
- php/commands/src/CLI_Command.php
Closes: https://github.com/EasyEngine/easyengine/issues/1125
> Add cli self-uninstall command

- php/class-ee-db.php
- php/class-ee-docker.php
Also add start and stop container commands
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Add cron table

- .travis.yml
- composer.json
- composer.lock
- php/EE/Loggers/Execution.php
- php/boot-fs.php
- phpcs.xml.dist
- utils/make-phar.php
Closes https://github.com/EasyEngine/easyengine/issues/1138
> Update minimum required php version

- composer.json
- composer.lock
> Add site-wp-command to composer

- features/cli.feature
Removing update tests till they are corrected as discussed in this [issue](https://github.com/EasyEngine/easyengine/issues/1144).
> Remove update tests

- VERSION
- php/EE/Migration/Containers.php
- php/EE/RevertableStepProcessor.php
- php/commands/src/CLI_Command.php
- php/utils.php
Upgrades containers to new version before upgrade.
> Container migration after update

- .gitignore
> Add .idea folder of phpstorm in gitignore

- php/site-utils.php
> Update site utils for postfix

- php/class-ee-db.php
- php/class-ee-site.php
> Update to support wildcard letsencrypt post refactoring

- .travis.yml
- ci/prepare.sh
- ci/test-commands.sh
> Add full test suite running

- README.md
Closes https://github.com/EasyEngine/easyengine/issues/1128
> Add info for tab completions

- .travis.yml
> Update travis flow and composer

- php/site-utils.php
> Fix bug caused in refactoring code syntax update

- php/EE/Runner.php
> Fix assoc-arg updates to apply only when site is primary arg

- .travis.yml
- ci/prepare.sh
- ci/test-env-install.sh
Closes https://github.com/EasyEngine/easyengine/issues/1183
> Update travis ci for nightly

- utils/make-phar.php
> Add specific json files to phar

- php/class-ee-site-letsencrypt.php
Copy chain file to enable ocsp stapling
refactor moveCertsToNginxProxy function
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Add OCSP stapling

- .travis.yml
- templates/global_docker_compose.yml.mustache
Signed-off-by: Kirtan Gajjar <kirtangajjar95@gmail.com>
> Update docker-compose.yml and .travis.yml

- php/EE/Model/Base.php
- php/class-ee-db.php
- php/class-ee.php
- php/utils.php
Additionally 
* it adds support for associative array in where condition
* Fixes `save()` method by adding `modified_on` column conditionally
> Add auth table

- php/class-ee.php
- php/utils.php
Closes: https://github.com/EasyEngine/easyengine/issues/1204
> Update for obfuscation in log file

- php/EE/Runner.php
Moved to https://github.com/EasyEngine/site-command/pull/112
> Move compatibility of site args to site-command

- utils/make-phar.php
> Add template folder for site-types in phar

- .travis.yml
- ci/test-env-install.sh
- features/bootstrap/FeatureContext.php
- php/EE/Migration/Containers.php
- php/EE/Runner.php
- php/class-ee.php
- php/init-ee.php
Closes: https://github.com/EasyEngine/easyengine/issues/1233
Depends on:
https://github.com/EasyEngine/config-command/pull/6
https://github.com/EasyEngine/auth-command/pull/13
https://github.com/EasyEngine/admin-tools-command/pull/18
https://github.com/EasyEngine/cron-command/pull/21
https://github.com/EasyEngine/site-command/pull/121
https://github.com/EasyEngine/site-type-wp/pull/54
https://github.com/EasyEngine/service-command/pull/11
https://github.com/EasyEngine/installer/pull/12
> Update UNIX paths of config,db,logs, and sites

- php/EE/Migration/Containers.php
Depends on: https://github.com/EasyEngine/cron-command/pull/25
> Update ee-cron-scheduler with constant

- migrations/db/20181016052850_easyengine_insert_docker_images_version.php
- php/EE/Migration/Executor.php
- php/class-ee-db.php
closes: https://github.com/EasyEngine/easyengine/issues/1254
Depends on: 
https://github.com/EasyEngine/site-command/pull/182
https://github.com/EasyEngine/cron-command/pull/35
https://github.com/EasyEngine/auth-command/pull/26
> Add 'type' column in migrations table and move db migrations path

- php/utils.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1261
This PR is needed to get nginx-proxy port from config.
> Add utility function to get values from config file

- php/EE/Migration/Base.php
Created to perform initial required checks and have most frequently required variables. For better support in migrations for migrations like: https://github.com/EasyEngine/cron-command/pull/37
> Update base migrations class

- php/commands/src/CLI_Command.php
Closes: https://github.com/EasyEngine/easyengine/issues/1281
> Fix process creation environment for cli update

- img-versions.json
Depends on https://github.com/EasyEngine/dockerfiles/pull/55
> Update docker image versions

- php/EE/Migration/SiteContainers.php
Issue ref: https://github.com/EasyEngine/site-command/issues/205
> Fix nohttps in docker-compose generation

- php/EE/Runner.php
Closes: https://github.com/EasyEngine/service-command/pull/33
Depends on: https://github.com/EasyEngine/dockerfiles/pull/59
Depends on: https://github.com/EasyEngine/service-command/pull/33
Depends on: https://github.com/EasyEngine/site-command/pull/210
> Update EasyEngine header on migration and version changes

- php/class-ee-docker.php
- php/class-ee.php
- php/commands/src/CLI_Command.php
- php/init-ee.php
Issue ref: https://github.com/EasyEngine/easyengine/issues/1059
> Add support for macOS

- php/EE/Migration/SiteContainers.php
- php/EE/Runner.php
Update migration functions and flow for: https://github.com/EasyEngine/site-command/pull/215
> Update migrations functions

- migrations/db/20181016052850_easyengine_insert_docker_images_version.php
Closes: https://github.com/EasyEngine/easyengine/issues/1292
> Add verbose output of image pulling

- php/EE/Runner.php
> Skip checks and migrations on 'ee help' and 'ee cli' commands

- php/EE/Migration/GlobalContainers.php
- php/EE/Runner.php
> Fix init checks

- php/EE/Dispatcher/Subcommand.php
- php/config-spec.php
Closes: https://github.com/EasyEngine/easyengine/issues/1217
> Remove global --prompt argument and respective code for same

- php/EE/Migration/SiteContainers.php
- php/class-ee.php
> Update to directly use static class

- php/EE/Runner.php
> Update docker requirement check

- img-versions.json
> Update to nginx-proxy with default Mozilla-Modern profile

- php/EE/Migration/Containers.php
- php/EE/Migration/GlobalContainers.php
- php/EE/Migration/SiteContainers.php
- php/init-ee.php
closes: https://github.com/EasyEngine/feature-requests/issues/1
Depends on: 
https://github.com/EasyEngine/service-command/pull/44
https://github.com/EasyEngine/site-command/pull/270
https://github.com/EasyEngine/site-type-php/pull/52
https://github.com/EasyEngine/site-type-wp/pull/130
> Feature: Zero downtime deploys.

- utils/make-phar.php
> Fix adding cloudflare dependency files to phar

- php/utils.php
issue: https://github.com/EasyEngine/easyengine/issues/1364
> Add get_value_if_flag_isset to utils

- php/utils.php
> Add utility function to sanitize file and folder name

- php/commands/src/CLI_Command.php
> Add log message to run EasyEngine updates safely

- php/EE/Runner.php
- php/init-ee.php
> Update nginx-proxy constant with container id

- php/class-ee.php
> Print stderr using error_log

- php/class-ee-docker.php
Issue ref: [EasyEngine/easyengine#1390](https://github.com/EasyEngine/easyengine/issues/1390)
> Update symlink creation in volumes

- php/EE/Migration/Containers.php
> Update migration pulling of images

- php/EE/Migration/GlobalContainers.php
> Fix nginx-proxy container name in migration

- README.md
Also, changed logo with banner and moved it to top
> Fixed broken EasyEngine logo link

- utils/make-phar.php
Signed-off-by: Riddhesh Sanghvi <riddhesh237@gmail.com>
> Update phar to include zip templates

- php/EE/Migration/Containers.php
Signed-off-by: Riddhesh Sanghvi <riddhesh237@gmail.com>
> Add extra and old docker images cleanup on update

- php/config-spec.php
For changes in https://github.com/EasyEngine/site-type-wp/pull/162
Signed-off-by: Riddhesh Sanghvi <riddhesh237@gmail.com>
> Add wp-mail config file option

- .travis.yml
- ci/test-commands.sh
- ci/test-env-install.sh
Update PHP version and modules to install
> Update travis prepration script

- php/config-spec.php
> Add sysctl option in global config

- .github/CONTRIBUTING.md
`CONTRIBUTING.md` has plenty of grammatical errors and typos. Fixed in this PR.
> Fix `CONTRIBUTING.md`

- php/EE/Migration/GlobalContainers.php
- php/EE/Runner.php
Depends on https://github.com/EasyEngine/service-command/pull/75
> Remove Nginx proxy id fecthing

- php/EE/Runner.php
- php/class-ee-docker.php
- php/config-spec.php
Closes: https://github.com/EasyEngine/easyengine/issues/1699
> Custom docker compose directory support

- .github/workflows/test_and_build.yml
- utils/changelog.sh
Closes: https://github.com/EasyEngine/easyengine/issues/1702
> Add auto release workflow

- .github/workflows/test_and_build.yml
- composer.json
- composer.lock
- utils/make-phar.php
Needed for failing DNS verify requests.
> Add daverandom libdns
